name: Deploy NestJS to Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env

      - name: Build Docker Image
        run: docker build --platform linux/amd64 --no-cache -t sakata1301/be-neo-brustalism:v0 .

      - name: Login DockerHub
        run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"

      - name: Push Docker Image
        run: docker push sakata1301/be-neo-brustalism:v0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy NestJS to Production Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
            docker pull sakata1301/be-neo-brustalism:v0
            docker image prune -f
            docker stop prod-be-neo-brustalism || true
            docker rm -f prod-be-neo-brustalism || true
            docker run -itd -p 8333:8333 --name prod-be-neo-brustalism sakata1301/be-neo-brustalism:v0
            # Nếu cần mount volume cho logs hoặc uploads:
            # docker run -itd -p 8333:8333 -v volume_nestjs_logs:/app/logs -v volume_nestjs_uploads:/app/uploads --name prod-be-neo-brustalism sakata1301/be-neo-brustalism:v0
